const projects=[
{title:'Water-Rocket Flight Lab',d:['Mechanical','Aerospace'],m:['Mechanics','Thermodynamics'],style:'Physical build',summary:'Design a reusable pressurised-water rocket and test how water volume, fin geometry and launch angle affect flight.',outcome:'A safe working prototype, flight dataset and engineering test report.',level:'Starter',weeks:3,cost:25,parts:['PET bottles','Cork + bicycle valve','Card fins','Phone slow-motion camera'],skills:['CAD','Experimental design','Data analysis'],steps:['Sketch and risk-assess the launcher','Build and baseline-test','Run a controlled experiment','Analyse results and present trade-offs'],cv:'Designed and experimentally validated a reusable water rocket, using controlled testing and data analysis to improve flight performance.'},
{title:'Smart Plant Guardian',d:['Electrical','Electronic','General'],m:['Programming','Circuits'],style:'Electronics',summary:'Build a sensor that measures soil moisture and warns when a plant needs water, with a simple status dashboard.',outcome:'A working sensor node, calibrated readings and a live dashboard.',level:'Starter',weeks:2,cost:20,parts:['Arduino-compatible board','Moisture sensor','LED or buzzer','Breadboard'],skills:['Embedded C','Circuits','Calibration'],steps:['Read raw sensor values','Calibrate dry and wet limits','Add alerts','Document accuracy and limitations'],cv:'Built and calibrated an embedded plant-monitoring system, translating sensor data into reliable real-time user alerts.'},
{title:'Desktop Wind Turbine',d:['Mechanical','Electrical','Aerospace'],m:['Mechanics','Circuits'],style:'Physical build',summary:'Create interchangeable turbine blades and measure which geometry generates the most electrical power in a desk-fan wind tunnel.',outcome:'A miniature generator and a defensible blade-design comparison.',level:'Intermediate',weeks:4,cost:35,parts:['Small DC motor','3D-printed/card blades','Multimeter','Wooden frame'],skills:['Prototyping','Power measurement','Optimisation'],steps:['Define blade variables','Build a safe test rig','Test three blade sets','Recommend an optimum design'],cv:'Optimised a small wind turbine through iterative prototyping, measuring electrical output across three blade geometries.'},
{title:'Bridge-in-a-Box Challenge',d:['Civil','Mechanical','General'],m:['Materials','Structures'],style:'Physical build',summary:'Design a lightweight bridge from low-cost materials, predict its failure load and test it to destruction.',outcome:'A tested structure, load-to-weight score and failure analysis.',level:'Starter',weeks:2,cost:15,parts:['Wooden sticks','PVA glue','Weights','Kitchen scale'],skills:['Statics','Material selection','Failure analysis'],steps:['Calculate reactions and member forces','Choose a truss layout','Build consistently','Load-test and explain failure'],cv:'Designed and load-tested a lightweight truss bridge, comparing analytical predictions with observed structural failure.'},
{title:'Room Energy Detective',d:['Electrical','Electronic','General'],m:['Programming','Thermodynamics'],style:'Data/software',summary:'Log temperature and light use to identify wasted energy, then model the impact of simple efficiency changes.',outcome:'A week of environmental data and an evidence-based energy plan.',level:'Starter',weeks:3,cost:15,parts:['Temperature/light sensor','Microcontroller','CSV spreadsheet','Optional Python notebook'],skills:['Python','Data visualisation','Energy analysis'],steps:['Plan sampling and privacy','Collect clean data','Find usage patterns','Model savings and communicate recommendations'],cv:'Developed an environmental data logger and analysed usage patterns to propose quantified room-energy improvements.'},
{title:'Line-Following Delivery Rover',d:['Electronic','Electrical','Mechanical'],m:['Programming','Circuits'],style:'Robotics',summary:'Build a small rover that follows a marked route and delivers a lightweight payload reliably.',outcome:'An autonomous prototype with measured speed and route-success rate.',level:'Intermediate',weeks:5,cost:55,parts:['Robot chassis','Two motors + driver','IR sensors','Microcontroller'],skills:['Control logic','Debugging','Systems integration'],steps:['Assemble drivetrain','Read and calibrate sensors','Tune steering control','Run repeatability trials'],cv:'Integrated sensors, motor control and embedded software to deliver an autonomous line-following rover with measured reliability.'},
{title:'Flood-Safe Street Model',d:['Civil','Environmental','General'],m:['Fluids','Materials'],style:'Physical build',summary:'Model a neighbourhood drainage system and compare permeable surfaces, channels and storage during simulated rainfall.',outcome:'A tabletop model and quantified comparison of flood interventions.',level:'Intermediate',weeks:4,cost:30,parts:['Foam board','Gravel and sponge','Measuring jug','Collection trays'],skills:['Fluid flow','Sustainable design','Measurement'],steps:['Map the catchment','Build a repeatable rain rig','Test three interventions','Recommend a combined solution'],cv:'Modelled urban flood mitigation strategies and quantified runoff reduction across three sustainable drainage interventions.'},
{title:'Assistive Grip Re-Design',d:['Biomedical','Mechanical','General'],m:['CAD','Materials'],style:'Design/CAD',summary:'Redesign an everyday handle for a user with limited grip strength, using ergonomic measurements and rapid prototypes.',outcome:'A user-centred CAD model, prototype and evaluation matrix.',level:'Starter',weeks:3,cost:20,parts:['Card/foam prototypes','Callipers','CAD software','Optional 3D print'],skills:['Human-centred design','CAD','Design evaluation'],steps:['Define user needs ethically','Measure and ideate','Prototype two concepts','Evaluate and refine'],cv:'Applied human-centred design and rapid prototyping to improve an everyday grip for users with reduced hand strength.'}
];
const values={discipline:['Any','General','Mechanical','Electrical','Electronic','Civil','Aerospace','Biomedical','Environmental'],module:['Any','Mechanics','Programming','Circuits','Materials','Structures','Thermodynamics','Fluids','CAD'],style:['Any','Physical build','Electronics','Robotics','Data/software','Design/CAD']};
for(const [id,list] of Object.entries(values)){document.querySelector('#'+id).innerHTML=list.map(x=>`<option>${x}</option>`).join('')}
const $=id=>document.getElementById(id),result=$('result');let seed=0;
function partUrl(part){const electronics=/Arduino|sensor|LED|buzzer|breadboard|motor|multimeter|microcontroller|robot|driver|IR/i.test(part),craft=/card|wood|stick|glue|foam/i.test(part),base=electronics?'https://thepihut.com/search?q=':craft?'https://www.hobbycraft.co.uk/search?q=':'https://www.amazon.co.uk/s?k=';return base+encodeURIComponent(part)}
function matches(){return projects.filter(p=>($('discipline').value==='Any'||p.d.includes($('discipline').value))&&($('module').value==='Any'||p.m.includes($('module').value))&&($('style').value==='Any'||p.style===$('style').value)&&p.cost<=+$('budget').value&&p.weeks<=+$('weeks').value)}
function render(scroll=false){const found=matches();if(!found.length){result.innerHTML='<div class="empty"><p class="label">NO EXACT MATCH — YET</p><h2>Give the project a little more room.</h2><p>Increase your budget or time, or choose “Any” for one filter.</p></div>';return}const p=found[seed%found.length];result.innerHTML=`<article class="result"><div class="result-head"><p class="label">YOUR PROJECT MATCH / ${String(seed%found.length+1).padStart(2,'0')}</p><h2>${p.title}</h2><p class="summary">${p.summary}</p></div><div class="chips"><span>${p.level}</span><span>${p.weeks} weeks</span><span>≈ £${p.cost}</span><span>${p.style}</span></div><div class="outcome"><b>THE FINISH LINE</b><p>${p.outcome}</p></div><div class="details"><div><h3>BUILD MILESTONES</h3><ol>${p.steps.map((x,i)=>`<li><b>${i+1}</b>${x}</li>`).join('')}</ol></div><div><h3>STARTER PARTS · BUY ONLINE</h3><ul class="parts">${p.parts.map(x=>`<li><a href="${partUrl(x)}" target="_blank" rel="noopener"><span>↳ ${x}</span><b>Shop ↗</b></a></li>`).join('')}</ul><p class="buy-note">Check your lab or reuse materials first. Links open UK suppliers; prices and availability may change.</p><h3 style="margin-top:38px">SKILLS YOU WILL PROVE</h3><div class="skills">${p.skills.map(x=>`<span>${x}</span>`).join('')}</div></div></div><blockquote class="cv"><b>CV STARTER</b>“${p.cv}”</blockquote><div class="actions"><button id="again">Try another idea ↻</button></div></article>`;$('again').onclick=()=>{seed++;render(true)};if(scroll)result.scrollIntoView({behavior:'smooth'})}
$('budget').oninput=e=>$('budgetOut').textContent='£'+e.target.value;$('weeks').oninput=e=>$('weeksOut').textContent=e.target.value+' weeks';$('filters').onsubmit=e=>{e.preventDefault();seed++;render(true)};['discipline','module','style','budget','weeks'].forEach(id=>$(id).addEventListener('change',()=>render()));render();
