'use client';
import { useMemo, useState } from 'react';

type Project = { title:string; discipline:string[]; modules:string[]; style:string; summary:string; outcome:string; difficulty:string; weeks:number; cost:number; parts:string[]; skills:string[]; milestones:string[]; cv:string };
const projects: Project[] = [
 {title:'Water-Rocket Flight Lab',discipline:['Mechanical','Aerospace'],modules:['Mechanics','Thermodynamics'],style:'Physical build',summary:'Design a reusable pressurised-water rocket and test how water volume, fin geometry and launch angle affect flight.',outcome:'A safe working prototype, flight dataset and engineering test report.',difficulty:'Starter',weeks:3,cost:25,parts:['PET bottles','Cork + bicycle valve','Card fins','Phone slow-motion camera'],skills:['CAD','Experimental design','Data analysis'],milestones:['Sketch and risk-assess the launcher','Build and baseline-test','Run a controlled experiment','Analyse results and present trade-offs'],cv:'Designed and experimentally validated a reusable water rocket, using controlled testing and data analysis to improve flight performance.'},
 {title:'Smart Plant Guardian',discipline:['Electrical','Electronic','General'],modules:['Programming','Circuits'],style:'Electronics',summary:'Build a sensor that measures soil moisture and warns when a plant needs water, with a simple status dashboard.',outcome:'A working sensor node, calibrated readings and a live dashboard.',difficulty:'Starter',weeks:2,cost:20,parts:['Arduino-compatible board','Moisture sensor','LED or buzzer','Breadboard'],skills:['Embedded C','Circuits','Calibration'],milestones:['Read raw sensor values','Calibrate dry and wet limits','Add alerts','Document accuracy and limitations'],cv:'Built and calibrated an embedded plant-monitoring system, translating sensor data into reliable real-time user alerts.'},
 {title:'Desktop Wind Turbine',discipline:['Mechanical','Electrical','Aerospace'],modules:['Mechanics','Circuits'],style:'Physical build',summary:'Create interchangeable turbine blades and measure which geometry generates the most electrical power in a desk-fan wind tunnel.',outcome:'A miniature generator and a defensible blade-design comparison.',difficulty:'Intermediate',weeks:4,cost:35,parts:['Small DC motor','3D-printed/card blades','Multimeter','Wooden frame'],skills:['Prototyping','Power measurement','Optimisation'],milestones:['Define blade variables','Build a safe test rig','Test three blade sets','Recommend an optimum design'],cv:'Optimised a small wind turbine through iterative prototyping, measuring electrical output across three blade geometries.'},
 {title:'Bridge-in-a-Box Challenge',discipline:['Civil','Mechanical','General'],modules:['Materials','Structures'],style:'Physical build',summary:'Design a lightweight bridge from low-cost materials, predict its failure load and test it to destruction.',outcome:'A tested structure, load-to-weight score and failure analysis.',difficulty:'Starter',weeks:2,cost:15,parts:['Wooden sticks','PVA glue','Weights','Kitchen scale'],skills:['Statics','Material selection','Failure analysis'],milestones:['Calculate reactions and member forces','Choose a truss layout','Build consistently','Load-test and explain failure'],cv:'Designed and load-tested a lightweight truss bridge, comparing analytical predictions with observed structural failure.'},
 {title:'Room Energy Detective',discipline:['Electrical','Electronic','General'],modules:['Programming','Thermodynamics'],style:'Data/software',summary:'Log temperature and light use to identify wasted energy, then model the impact of simple efficiency changes.',outcome:'A week of environmental data and an evidence-based energy plan.',difficulty:'Starter',weeks:3,cost:15,parts:['Temperature/light sensor','Microcontroller','CSV spreadsheet','Optional Python notebook'],skills:['Python','Data visualisation','Energy analysis'],milestones:['Plan sampling and privacy','Collect clean data','Find usage patterns','Model savings and communicate recommendations'],cv:'Developed an environmental data logger and analysed usage patterns to propose quantified room-energy improvements.'},
 {title:'Line-Following Delivery Rover',discipline:['Electronic','Electrical','Mechanical'],modules:['Programming','Circuits'],style:'Robotics',summary:'Build a small rover that follows a marked route and delivers a lightweight payload reliably.',outcome:'An autonomous prototype with measured speed and route-success rate.',difficulty:'Intermediate',weeks:5,cost:55,parts:['Robot chassis','Two motors + driver','IR sensors','Microcontroller'],skills:['Control logic','Debugging','Systems integration'],milestones:['Assemble drivetrain','Read and calibrate sensors','Tune steering control','Run repeatability trials'],cv:'Integrated sensors, motor control and embedded software to deliver an autonomous line-following rover with measured reliability.'},
 {title:'Flood-Safe Street Model',discipline:['Civil','Environmental','General'],modules:['Fluids','Materials'],style:'Physical build',summary:'Model a neighbourhood drainage system and compare permeable surfaces, channels and storage during simulated rainfall.',outcome:'A tabletop model and quantified comparison of flood interventions.',difficulty:'Intermediate',weeks:4,cost:30,parts:['Foam board','Gravel and sponge','Measuring jug','Collection trays'],skills:['Fluid flow','Sustainable design','Measurement'],milestones:['Map the catchment','Build a repeatable rain rig','Test three interventions','Recommend a combined solution'],cv:'Modelled urban flood mitigation strategies and quantified runoff reduction across three sustainable drainage interventions.'},
 {title:'Assistive Grip Re-Design',discipline:['Biomedical','Mechanical','General'],modules:['CAD','Materials'],style:'Design/CAD',summary:'Redesign an everyday handle for a user with limited grip strength, using ergonomic measurements and rapid prototypes.',outcome:'A user-centred CAD model, prototype and evaluation matrix.',difficulty:'Starter',weeks:3,cost:20,parts:['Card/foam prototypes','Callipers','CAD software','Optional 3D print'],skills:['Human-centred design','CAD','Design evaluation'],milestones:['Define user needs ethically','Measure and ideate','Prototype two concepts','Evaluate and refine'],cv:'Applied human-centred design and rapid prototyping to improve an everyday grip for users with reduced hand strength.'}
];
const disciplines=['Any','General','Mechanical','Electrical','Electronic','Civil','Aerospace','Biomedical','Environmental'];
const modules=['Any','Mechanics','Programming','Circuits','Materials','Structures','Thermodynamics','Fluids','CAD'];

export default function Home(){
 const [discipline,setDiscipline]=useState('Any'),[module,setModule]=useState('Any'),[budget,setBudget]=useState(40),[weeks,setWeeks]=useState(4),[style,setStyle]=useState('Any'),[seed,setSeed]=useState(0),[saved,setSaved]=useState(false);
 const matches=useMemo(()=>projects.filter(p=>(discipline==='Any'||p.discipline.includes(discipline))&&(module==='Any'||p.modules.includes(module))&&p.cost<=budget&&p.weeks<=weeks&&(style==='Any'||p.style===style)),[discipline,module,budget,weeks,style]);
 const project=matches.length?matches[seed%matches.length]:null;
 function generate(){setSeed(s=>s+1);setSaved(false);document.getElementById('result')?.scrollIntoView({behavior:'smooth',block:'start'})}
 return <main>
  <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">∑</span> Buildfolio</a><a href="#how">How it works</a><a href="#generator">Idea generator</a><span className="nav-pill">Made for year one</span></nav>
  <section className="hero" id="top"><div className="eyebrow"><span/> FROM MODULE TO PORTFOLIO</div><h1>Build something<br/><em>worth talking about.</em></h1><p className="hero-copy">Turn the subjects you are already learning into a practical engineering project—complete with a build plan, parts list and CV-ready story.</p><a className="primary" href="#generator">Find my project <span>↘</span></a><div className="hero-stats"><div><strong>8</strong><span>curated ideas</span></div><div><strong>£15+</strong><span>student budgets</span></div><div><strong>2–5</strong><span>week builds</span></div></div><div className="orbit" aria-hidden="true"><div className="orbital o1"/><div className="orbital o2"/><div className="planet">PROJECT<br/><b>01</b></div><span className="tag t1">DESIGN</span><span className="tag t2">TEST</span><span className="tag t3">ITERATE</span></div></section>
  <section className="how" id="how"><p className="section-label">A BETTER STARTING POINT</p><div className="how-grid"><h2>Your coursework is<br/>full of good ideas.</h2><p>You do not need to invent the next rocket company. A strong first-year project shows curiosity, a clear process and evidence that you can turn theory into something real.</p></div><div className="steps"><article><b>01</b><h3>Choose your context</h3><p>Tell us your discipline, current module, time and budget.</p></article><article><b>02</b><h3>Get a buildable brief</h3><p>Receive a scoped idea with materials and measurable outcomes.</p></article><article><b>03</b><h3>Tell the story</h3><p>Use the milestones and CV sentence to document your work.</p></article></div></section>
  <section className="generator" id="generator"><div className="generator-head"><p className="section-label light">PROJECT GENERATOR / BETA</p><h2>What do you want<br/>to make real?</h2></div><div className="controls">
   <label>Engineering discipline<select value={discipline} onChange={e=>setDiscipline(e.target.value)}>{disciplines.map(x=><option key={x}>{x}</option>)}</select></label><label>Module to connect<select value={module} onChange={e=>setModule(e.target.value)}>{modules.map(x=><option key={x}>{x}</option>)}</select></label><label>Build style<select value={style} onChange={e=>setStyle(e.target.value)}>{['Any','Physical build','Electronics','Robotics','Data/software','Design/CAD'].map(x=><option key={x}>{x}</option>)}</select></label><label>Maximum budget <output>£{budget}</output><input aria-label="Maximum budget" type="range" min="15" max="75" step="5" value={budget} onChange={e=>setBudget(+e.target.value)}/></label><label>Time available <output>{weeks} weeks</output><input aria-label="Time available" type="range" min="2" max="6" value={weeks} onChange={e=>setWeeks(+e.target.value)}/></label><button className="generate" onClick={generate}>Generate my idea <span>→</span></button>
  </div></section>
  <section className="result-wrap" id="result">{project?<article className="result-card"><div className="result-top"><div><p className="section-label">YOUR PROJECT MATCH / {String(seed%matches.length+1).padStart(2,'0')}</p><h2>{project.title}</h2><p className="summary">{project.summary}</p></div><button className={saved?'save saved':'save'} onClick={()=>setSaved(!saved)}>{saved?'✓ Saved':'♡ Save idea'}</button></div><div className="chips"><span>{project.difficulty}</span><span>{project.weeks} weeks</span><span>≈ £{project.cost}</span><span>{project.style}</span></div><div className="outcome"><b>THE FINISH LINE</b><p>{project.outcome}</p></div><div className="detail-grid"><div><h3>Build milestones</h3><ol>{project.milestones.map((x,i)=><li key={x}><b>{i+1}</b>{x}</li>)}</ol></div><div><h3>Starter parts</h3><ul>{project.parts.map(x=><li key={x}>↳ {x}</li>)}</ul><h3 className="skill-title">Skills you will prove</h3><div className="skill-list">{project.skills.map(x=><span key={x}>{x}</span>)}</div></div></div><blockquote><span>CV STARTER</span>“{project.cv}”</blockquote><div className="result-actions"><button onClick={generate}>Try another idea ↻</button><a href={`data:text/plain;charset=utf-8,${encodeURIComponent(project.title+'\n\n'+project.summary+'\n\nMilestones:\n- '+project.milestones.join('\n- ')+'\n\nCV: '+project.cv)}`} download={`${project.title.toLowerCase().replaceAll(' ','-')}.txt`}>Download brief ↓</a></div></article>:<div className="empty"><p className="section-label">NO EXACT MATCH — YET</p><h2>Give the project a little more room.</h2><p>Try increasing your budget or time, or choose “Any” for one of the filters.</p></div>}</section>
  <footer><a className="brand" href="#top"><span className="brand-mark">∑</span> Buildfolio</a><p>Small projects. Serious potential.</p><span>Built for curious engineers.</span></footer>
 </main>
}
